'use strict';

/**
 * WalletCreationEngine
 *
 * High-level wallet creation and management for trustees, beneficiaries,
 * operators, and external linked wallets. Wraps WalletEngine so the FinOps UI
 * has a clean dedicated endpoint namespace.
 */

const { WalletEngine } = require('./walletEngine');

let DappEngine;
try { ({ DappEngine } = require('./dappEngine')); } catch (e) { DappEngine = null; }

function id(prefix = 'WC') { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; }

class WalletCreationEngine {
  static async _ensureUser(userIdOrEmail) {
    if (!userIdOrEmail) throw new Error('userId or email required');
    if (DappEngine) {
      const byId = await DappEngine.getUser(userIdOrEmail).catch(() => null);
      if (byId) return byId.id;
      const byEmail = await DappEngine.getUserByEmail(userIdOrEmail).catch(() => null);
      if (byEmail) return byEmail.id;
      const created = await DappEngine.createUser({ email: userIdOrEmail, name: userIdOrEmail, role: 'beneficiary', roles: ['beneficiary'], activeRole: 'beneficiary' });
      return created.id;
    }
    throw new Error('DappEngine not available');
  }

  static async createWallet({ userId, email, name, type = 'internal', address, privateKey, subtype, metadata = {} } = {}) {
    let uid = userId;
    if (!uid && email) uid = await this._ensureUser(email);
    if (!uid) throw new Error('userId or email required');
    return WalletEngine.createWallet({ userId: uid, name: name || 'Trust Wallet', type, address, privateKey, subtype, metadata });
  }

  static async createOperatorWallet({ name = 'Operator Wallet', subtype = 'operator', metadata = {} } = {}) {
    if (DappEngine) {
      const user = await DappEngine.getUserByEmail('operator@dlbtrust.local').catch(() => null)
        || await DappEngine.createUser({ email: 'operator@dlbtrust.local', name: 'Operator', role: 'operator', roles: ['operator'], activeRole: 'operator' });
      return WalletEngine.createWallet({ userId: user.id, name, type: 'internal', subtype, metadata: { ...metadata, operator: true } });
    }
    throw new Error('DappEngine not available');
  }

  static async importWallet({ userId, email, name, address, privateKey, subtype, metadata = {} } = {}) {
    if (!address) throw new Error('address required for import');
    return this.createWallet({ userId, email, name: name || 'Imported Wallet', type: 'external', address, privateKey, subtype, metadata });
  }

  static async listWallets({ userId, type, subtype } = {}) {
    const all = await WalletEngine.listWallets();
    return all.filter(w => {
      if (userId && w.user_id !== userId) return false;
      if (type && w.type !== type) return false;
      const meta = typeof w.metadata === 'string' ? JSON.parse(w.metadata || '{}') : (w.metadata || {});
      if (subtype && meta.subtype !== subtype) return false;
      return true;
    });
  }

  static async getWallet(id) {
    return WalletEngine.getWallet(id);
  }

  static async getWalletByAddress(address) {
    return WalletEngine.getWalletByAddress(address);
  }

  static async getWalletBalance(id, asset) {
    return WalletEngine.getBalance(id, asset);
  }

  static async info() {
    return {
      canCreateInternal: true,
      canCreateExternal: true,
      note: 'Internal wallets are generated by the system; external wallets are linked addresses.',
    };
  }
}

module.exports = { WalletCreationEngine };
