'use strict';

/**
 * WalletEngine
 *
 * Creates and manages wallets for trustees and beneficiaries. Each user can
 * have one or more wallets. Internal wallets are generated by the system and
 * their private keys are encrypted at rest. External wallets are addresses the
 * user has linked (e.g. MetaMask).
 *
 * Supports:
 * - Internal ledger transfers between system wallets
 * - External gasless meta-transactions using the ERC-2771 trusted forwarder
 * - SIT minting/funding from the trust's source-of-funds ledgers
 */

const crypto = require('crypto');
let viem, chains;
try { viem = require('viem'); chains = require('viem/chains'); } catch (e) { viem = null; chains = null; }
let accountFns;
try { accountFns = require('viem/accounts'); } catch (e) { accountFns = null; }

let pool;
try { pool = require('../bonds/pgPool'); } catch (e) { pool = null; }

let DappEngine, SovereignTrustEngine;
function getDappEngine() { try { return require('./dappEngine').DappEngine; } catch (e) { return null; } }
function getSovereignEngine() { try { return require('./sovereignTrustEngine').SovereignTrustEngine; } catch (e) { return null; } }

const { getConfig } = require('./config');

function str(name, def = '') { return (process.env[name] || def).trim(); }
function bool(name, def = false) { const v = process.env[name]; return v ? String(v).toLowerCase() === 'true' : def; }
function id(prefix = 'WLT') { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; }
function toCents(amount) { return Math.round((Number(amount) || 0) * 100); }
function fromCents(cents) { return (cents / 100).toFixed(2); }

async function query(sql, params) {
  if (!pool) throw new Error('Postgres unavailable');
  return pool.query(sql, params);
}

async function withFallback(fn, fallback) { try { return await fn(); } catch (e) { if (!pool) return fallback(e); throw e; } }

class WalletEngine {
  static _encryptionKey() {
    const secret = process.env.WALLET_ENCRYPTION_KEY || process.env.JWT_SECRET || process.env.ADMIN_SECRET_TOKEN || '';
    if (!secret) throw new Error('WALLET_ENCRYPTION_KEY, JWT_SECRET or ADMIN_SECRET_TOKEN required for wallet key encryption');
    return crypto.scryptSync(secret, 'dlbtrust-wallet-salt', 32);
  }

  static _encrypt(plaintext) {
    const iv = crypto.randomBytes(16);
    const cipher = crypto.createCipheriv('aes-256-gcm', this._encryptionKey(), iv);
    let encrypted = cipher.update(plaintext, 'utf8', 'hex');
    encrypted += cipher.final('hex');
    const tag = cipher.getAuthTag();
    return `${iv.toString('hex')}:${tag.toString('hex')}:${encrypted}`;
  }

  static _decrypt(ciphertext) {
    const [ivHex, tagHex, encrypted] = (ciphertext || '').split(':');
    if (!ivHex || !tagHex || !encrypted) throw new Error('Invalid encrypted wallet key');
    const decipher = crypto.createDecipheriv('aes-256-gcm', this._encryptionKey(), Buffer.from(ivHex, 'hex'));
    decipher.setAuthTag(Buffer.from(tagHex, 'hex'));
    let decrypted = decipher.update(encrypted, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    return decrypted;
  }

  static _generateKeyPair() {
    if (!accountFns || !accountFns.generatePrivateKey) throw new Error('viem/accounts not available');
    const privateKey = accountFns.generatePrivateKey();
    const account = accountFns.privateKeyToAccount(privateKey);
    return { privateKey, address: account.address };
  }

  static async ensureTables() {
    if (!pool) return;
    await query(`
      CREATE TABLE IF NOT EXISTS dapp_wallets (
        id TEXT PRIMARY KEY,
        user_id TEXT REFERENCES dapp_users(id) ON DELETE CASCADE,
        name TEXT,
        address TEXT NOT NULL,
        chain TEXT NOT NULL DEFAULT 'evm',
        type TEXT NOT NULL DEFAULT 'internal',
        private_key_encrypted TEXT,
        is_primary BOOLEAN NOT NULL DEFAULT true,
        metadata JSONB DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    await query(`CREATE INDEX IF NOT EXISTS idx_dapp_wallets_user ON dapp_wallets(user_id);`);
    await query(`CREATE INDEX IF NOT EXISTS idx_dapp_wallets_address ON dapp_wallets(address);`);

    await query(`
      CREATE TABLE IF NOT EXISTS dapp_wallet_balances (
        id TEXT PRIMARY KEY,
        wallet_id TEXT REFERENCES dapp_wallets(id) ON DELETE CASCADE,
        asset TEXT NOT NULL,
        balance_cents BIGINT NOT NULL DEFAULT 0,
        UNIQUE(wallet_id, asset)
      );
    `);

    await query(`
      CREATE TABLE IF NOT EXISTS dapp_wallet_transactions (
        id TEXT PRIMARY KEY,
        wallet_id TEXT NOT NULL,
        counterparty_wallet_id TEXT,
        counterparty_address TEXT,
        type TEXT NOT NULL,
        asset TEXT NOT NULL,
        amount_cents BIGINT NOT NULL,
        status TEXT NOT NULL DEFAULT 'completed',
        tx_hash TEXT,
        memo TEXT,
        metadata JSONB DEFAULT '{}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    await query(`CREATE INDEX IF NOT EXISTS idx_dapp_wallet_tx_wallet ON dapp_wallet_transactions(wallet_id);`);
  }

  static async ensureWalletsForAllUsers() {
    await this.ensureTables();
    DappEngine = getDappEngine();
    if (!DappEngine) throw new Error('DappEngine not available');
    const users = await DappEngine.listUsers();
    const results = [];
    for (const u of users) {
      if (!u) continue;
      const wallets = await this.getWalletsByUser(u.id);
      if (!wallets.length) {
        const wallet = await this.createWallet({ userId: u.id, name: `${u.name || u.email} Wallet`, type: 'internal' });
        await DappEngine.linkWallet({ email: u.email, walletAddress: wallet.address, provider: 'system' }).catch(() => null);
        results.push(wallet);
      }
    }
    return results;
  }

  static async getSystemUser() {
    DappEngine = getDappEngine();
    if (!DappEngine) throw new Error('DappEngine not available');
    const email = 'system@dlbtrust.internal';
    let user = await DappEngine.getUserByEmail(email).catch(() => null);
    if (!user) {
      user = await DappEngine.createUser({ email, name: 'Trust System', role: 'system', roles: ['system'], activeRole: 'system' });
    }
    return user;
  }

  static async createWallet({ userId, name, type = 'internal', address, privateKey, subtype, metadata = {} } = {}) {
    await this.ensureTables();
    if (!userId) throw new Error('userId required');
    let walletAddress = address;
    let encryptedKey = null;
    if (type === 'internal') {
      const kp = this._generateKeyPair();
      walletAddress = kp.address;
      encryptedKey = this._encrypt(kp.privateKey);
    }
    if (!walletAddress) throw new Error('address required for external wallet');
    const meta = { createdBy: 'WalletEngine', ...(metadata || {}), ...(subtype ? { subtype } : {}) };
    const row = {
      id: id('WLT'),
      user_id: userId,
      name: name || 'Wallet',
      address: viem && viem.getAddress ? viem.getAddress(walletAddress) : walletAddress.toLowerCase(),
      chain: 'evm',
      type,
      private_key_encrypted: encryptedKey,
      is_primary: true,
      metadata: JSON.stringify(meta),
    };
    await withFallback(async () => {
      await query(`INSERT INTO dapp_wallets (id, user_id, name, address, chain, type, private_key_encrypted, is_primary, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
        [row.id, row.user_id, row.name, row.address, row.chain, row.type, row.private_key_encrypted, row.is_primary, row.metadata]);
    }, () => {});
    return row;
  }

  static async getWalletBySubtype(subtype) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query(`SELECT * FROM dapp_wallets WHERE metadata->>'subtype' = $1 LIMIT 1`, [subtype]);
      return rows.rows[0] || null;
    }, () => null);
  }

  static async getWallet(id) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query('SELECT * FROM dapp_wallets WHERE id = $1 LIMIT 1', [id]);
      return rows.rows[0] || null;
    }, () => null);
  }

  static async getWalletByAddress(address) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query('SELECT * FROM dapp_wallets WHERE address ILIKE $1 LIMIT 1', [address]);
      return rows.rows[0] || null;
    }, () => null);
  }

  static async getWalletsByUser(userId) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query('SELECT * FROM dapp_wallets WHERE user_id = $1 ORDER BY is_primary DESC, created_at DESC', [userId]);
      return rows.rows;
    }, () => []);
  }

  static async listWallets() {
    await this.ensureTables();
    DappEngine = getDappEngine();
    const users = DappEngine ? await DappEngine.listUsers() : [];
    const userMap = new Map(users.map(u => [u.id, u]));
    return withFallback(async () => {
      const rows = await query('SELECT w.*, u.email, u.name as user_name, u.role FROM dapp_wallets w LEFT JOIN dapp_users u ON w.user_id = u.id ORDER BY u.name, w.is_primary DESC');
      return rows.rows.map(r => ({ ...r, user: userMap.get(r.user_id) || null }));
    }, () => []);
  }

  static async _ensureBalance(walletId, asset) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query('SELECT * FROM dapp_wallet_balances WHERE wallet_id = $1 AND asset = $2', [walletId, asset.toUpperCase()]);
      if (rows.rows.length) return rows.rows[0];
      const newId = id('WBL');
      await query('INSERT INTO dapp_wallet_balances (id, wallet_id, asset, balance_cents) VALUES ($1,$2,$3,0)', [newId, walletId, asset.toUpperCase()]);
      return { id: newId, wallet_id: walletId, asset: asset.toUpperCase(), balance_cents: 0 };
    }, () => ({ id: 'mem', wallet_id: walletId, asset: asset.toUpperCase(), balance_cents: 0 }));
  }

  static async _setBalance(walletId, asset, cents) {
    await this._ensureBalance(walletId, asset);
    await withFallback(async () => {
      await query('UPDATE dapp_wallet_balances SET balance_cents = $1 WHERE wallet_id = $2 AND asset = $3', [cents, walletId, asset.toUpperCase()]);
    }, () => {});
  }

  static async _credit(walletId, asset, cents, metadata = {}) {
    const bal = await this._ensureBalance(walletId, asset);
    const newCents = Number(bal.balance_cents) + cents;
    await this._setBalance(walletId, asset, newCents);
    const txId = id('WTX');
    await withFallback(async () => {
      await query('INSERT INTO dapp_wallet_transactions (id, wallet_id, type, asset, amount_cents, status, memo, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',
        [txId, walletId, 'credit', asset.toUpperCase(), cents, 'completed', metadata.memo || '', JSON.stringify(metadata)]);
    }, () => {});
    return this.getBalance(walletId);
  }

  static async _debit(walletId, asset, cents, metadata = {}) {
    const bal = await this._ensureBalance(walletId, asset);
    if (Number(bal.balance_cents) < cents) throw new Error(`Insufficient ${asset.toUpperCase()} internal balance: ${fromCents(Number(bal.balance_cents))} available`);
    const newCents = Number(bal.balance_cents) - cents;
    await this._setBalance(walletId, asset, newCents);
    const txId = id('WTX');
    await withFallback(async () => {
      await query('INSERT INTO dapp_wallet_transactions (id, wallet_id, type, asset, amount_cents, status, memo, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',
        [txId, walletId, 'debit', asset.toUpperCase(), cents, 'completed', metadata.memo || '', JSON.stringify(metadata)]);
    }, () => {});
    return this.getBalance(walletId);
  }

  // Public ledger helpers for master-wallet automation
  static async credit(walletId, asset, amount, metadata = {}) {
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');
    return this._credit(walletId, asset, cents, metadata);
  }

  static async debit(walletId, asset, amount, metadata = {}) {
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');
    return this._debit(walletId, asset, cents, metadata);
  }

  static async getBalance(walletId) {
    const wallet = await this.getWallet(walletId);
    if (!wallet) throw new Error('Wallet not found');
    SovereignTrustEngine = getSovereignEngine();
    const internalBalances = await withFallback(async () => {
      const rows = await query('SELECT asset, balance_cents FROM dapp_wallet_balances WHERE wallet_id = $1', [walletId]);
      const map = {};
      for (const r of rows.rows) map[r.asset] = Number(r.balance_cents);
      return map;
    }, () => ({}));

    const external = { eth: '0', usdc: '0', sit: '0' };
    if (viem && viem.isAddress && viem.isAddress(wallet.address)) {
      try {
        const cfg = (SovereignTrustEngine && SovereignTrustEngine.getConfig) ? SovereignTrustEngine.getConfig() : {};
        const publicClient = this._publicClient(cfg);
        if (publicClient) {
          const [ethWei, usdcRaw] = await Promise.all([
            publicClient.getBalance({ address: wallet.address }).catch(() => 0n),
            publicClient.readContract({ address: cfg.usdcAddress, abi: this._erc20Abi(), functionName: 'balanceOf', args: [wallet.address] }).catch(() => 0n),
          ]);
          external.eth = viem.formatEther(ethWei);
          external.usdc = viem.formatUnits(usdcRaw, 6);
        }
      } catch (e) { console.warn('[WalletEngine] external balance fetch failed:', e.message); }

      try {
        if (SovereignTrustEngine && SovereignTrustEngine.tokenBalanceOf) {
          external.sit = await SovereignTrustEngine.tokenBalanceOf(wallet.address);
        }
      } catch (e) { console.warn('[WalletEngine] SIT balance fetch failed:', e.message); }
    }

    return {
      walletId,
      address: wallet.address,
      internal: Object.fromEntries(Object.entries(internalBalances).map(([a, c]) => [a, fromCents(c)])),
      external,
    };
  }

  static _publicClient(cfg) {
    if (!viem || !cfg || !cfg.rpcUrl) return null;
    const chain = cfg.chainId === 11155111 ? chains.sepolia : (cfg.chainId === 1 ? chains.mainnet : chains.mainnet);
    return viem.createPublicClient({ chain, transport: viem.http(cfg.rpcUrl) });
  }

  static _erc20Abi() {
    return [
      { type: 'function', name: 'balanceOf', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
      { type: 'function', name: 'decimals', inputs: [], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
    ];
  }

  static async fundWallet({ walletId, amount, asset = 'SIT', sourceType = 'treasury', sourceAccountId = 'TREASURY_HOT', memo } = {}) {
    await this.ensureTables();
    const wallet = await this.getWallet(walletId);
    if (!wallet) throw new Error('Wallet not found');
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');
    SovereignTrustEngine = getSovereignEngine();

    if (asset.toUpperCase() === 'SIT' && SovereignTrustEngine) {
      await SovereignTrustEngine.whitelistAddress(wallet.address, true).catch(() => null);
      const mint = await SovereignTrustEngine.mintFromSource({ sourceType, sourceAccountId, to: wallet.address, amount, memo });
      await this._credit(walletId, 'SIT', cents, { memo: memo || `Fund wallet ${walletId}`, mint });
      return { wallet, amount, asset: 'SIT', mint, balance: await this.getBalance(walletId) };
    }

    await this._credit(walletId, asset, cents, { memo: memo || `Credit ${asset}` });
    return { wallet, amount, asset, balance: await this.getBalance(walletId) };
  }

  static async fundWalletEth({ walletId, amountEth } = {}) {
    if (!viem) throw new Error('viem not installed');
    const wallet = await this.getWallet(walletId);
    if (!wallet) throw new Error('Wallet not found');
    const cfg = getConfig();
    if (!cfg.privateKey) throw new Error('DAPP_PRIVATE_KEY not configured');
    const account = accountFns.privateKeyToAccount(cfg.privateKey);
    const chain = cfg.chainId === 11155111 ? chains.sepolia : chains.mainnet;
    const fees = { maxFeePerGas: viem.parseGwei('1.5'), maxPriorityFeePerGas: viem.parseGwei('0.0015') };
    const walletClient = viem.createWalletClient({ account, chain, transport: viem.http(cfg.rpcUrl) });
    const publicClient = viem.createPublicClient({ chain, transport: viem.http(cfg.rpcUrl) });
    const raw = viem.parseEther(String(amountEth));
    const hash = await walletClient.sendTransaction({ to: wallet.address, value: raw, gas: 21000n, ...fees });
    await publicClient.waitForTransactionReceipt({ hash });
    return { walletId, amountEth, txHash: hash };
  }

  static async transfer({ fromWalletId, toWalletId, toAddress, amount, asset = 'SIT', memo } = {}) {
    await this.ensureTables();
    if (!fromWalletId || (!toWalletId && !toAddress)) throw new Error('fromWalletId and (toWalletId or toAddress) required');
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');

    if (toWalletId) {
      const fromWallet = await this.getWallet(fromWalletId);
      const toWallet = await this.getWallet(toWalletId);
      if (!fromWallet || !toWallet) throw new Error('Wallet not found');
      await this._debit(fromWalletId, asset, cents, { memo: memo || `Transfer to ${toWalletId}` });
      await this._credit(toWalletId, asset, cents, { memo: memo || `Transfer from ${fromWalletId}` });
      const txId = id('WTX');
      await withFallback(async () => {
        await query('INSERT INTO dapp_wallet_transactions (id, wallet_id, counterparty_wallet_id, type, asset, amount_cents, status, memo) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',
          [txId, fromWalletId, toWalletId, 'internal', asset.toUpperCase(), cents, 'completed', memo || '']);
      }, () => {});
      return { type: 'internal', from: fromWalletId, to: toWalletId, amount, asset, balance: await this.getBalance(fromWalletId) };
    }

    // External transfer
    return this.externalSend({ fromWalletId, toAddress, amount, asset, memo });
  }

  static async externalSend({ fromWalletId, toAddress, amount, asset = 'SIT', memo } = {}) {
    await this.ensureTables();
    if (!fromWalletId || !toAddress) throw new Error('fromWalletId and toAddress required');
    if (!viem || !viem.isAddress || !viem.isAddress(toAddress)) throw new Error('Invalid recipient address');
    const to = viem.getAddress ? viem.getAddress(toAddress) : toAddress.toLowerCase();
    const wallet = await this.getWallet(fromWalletId);
    if (!wallet) throw new Error('Wallet not found');
    if (wallet.type !== 'internal' || !wallet.private_key_encrypted) throw new Error('Only system wallets can send external transactions');
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');

    SovereignTrustEngine = getSovereignEngine();
    if (!SovereignTrustEngine || !SovereignTrustEngine.buildMetaTx || !SovereignTrustEngine.relayMetaTx) {
      throw new Error('SovereignTrustEngine meta-transaction support not available');
    }

    const internalBalance = await this._ensureBalance(fromWalletId, asset);
    if (Number(internalBalance.balance_cents) < cents) throw new Error(`Insufficient ${asset} internal balance`);

    const onChainBalance = await SovereignTrustEngine.tokenBalanceOf(wallet.address);
    if (Number(onChainBalance) * 100 < cents) throw new Error(`Insufficient on-chain ${asset} balance. Fund the wallet first.`);

    await SovereignTrustEngine.whitelistAddress(to, true).catch(() => null);
    const metaTx = await SovereignTrustEngine.buildMetaTx({
      from: wallet.address,
      functionName: 'transfer',
      args: [to],
      amount: amount,
    });

    const account = accountFns.privateKeyToAccount(this._decrypt(wallet.private_key_encrypted));
    const message = {
      from: metaTx.message.from,
      to: metaTx.message.to,
      value: BigInt(metaTx.message.value || 0),
      gas: BigInt(metaTx.message.gas || 0),
      nonce: BigInt(metaTx.message.nonce || 0),
      data: metaTx.message.data,
    };
    const signature = await account.signTypedData({
      domain: metaTx.domain,
      types: metaTx.types,
      primaryType: 'ForwardRequest',
      message,
    });

    const relay = await SovereignTrustEngine.relayMetaTx({ request: metaTx.forwardRequest, signature });

    await this._debit(fromWalletId, asset, cents, { memo: memo || `External send to ${to}`, tx_hash: relay.tx });
    const txId = id('WTX');
    await withFallback(async () => {
      await query('INSERT INTO dapp_wallet_transactions (id, wallet_id, counterparty_address, type, asset, amount_cents, status, tx_hash, memo, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',
        [txId, fromWalletId, to, 'external', asset.toUpperCase(), cents, 'completed', relay.tx, memo || '', JSON.stringify(relay)]);
    }, () => {});

    return { type: 'external', from: wallet.address, to, amount, asset, txHash: relay.tx, balance: await this.getBalance(fromWalletId) };
  }

  static async externalTokenSend({ fromWalletId, toAddress, amount, asset = 'USDC', tokenAddress, decimals = 6, memo } = {}) {
    await this.ensureTables();
    if (!fromWalletId || !toAddress || !tokenAddress) throw new Error('fromWalletId, toAddress and tokenAddress required');
    if (!viem || !viem.isAddress || !viem.isAddress(toAddress) || !viem.isAddress(tokenAddress)) throw new Error('Invalid recipient or token address');
    const to = viem.getAddress ? viem.getAddress(toAddress) : toAddress.toLowerCase();
    const wallet = await this.getWallet(fromWalletId);
    if (!wallet || wallet.type !== 'internal' || !wallet.private_key_encrypted) throw new Error('Only system wallets can send external tokens');
    const cents = toCents(amount);
    if (cents <= 0) throw new Error('amount must be positive');

    const cfg = getConfig();
    if (!cfg.privateKey) throw new Error('DAPP_PRIVATE_KEY not configured');
    const chain = cfg.chainId === 11155111 ? chains.sepolia : chains.mainnet;
    const account = accountFns.privateKeyToAccount(this._decrypt(wallet.private_key_encrypted));
    const walletClient = viem.createWalletClient({ account, chain, transport: viem.http(cfg.rpcUrl) });
    const publicClient = viem.createPublicClient({ chain, transport: viem.http(cfg.rpcUrl) });
    const raw = viem.parseUnits(String(amount), decimals);
    const fees = { maxFeePerGas: viem.parseGwei('3'), maxPriorityFeePerGas: viem.parseGwei('0.0015') };

    const hash = await walletClient.writeContract({
      address: tokenAddress,
      abi: this._erc20FullAbi(),
      functionName: 'transfer',
      args: [to, raw],
      gas: 100000n,
      ...fees,
    });
    const receipt = await publicClient.waitForTransactionReceipt({ hash });
    if (receipt.status !== 'success') throw new Error('Token transfer reverted');

    await this._debit(fromWalletId, asset, cents, { memo: memo || `External token send to ${to}`, tx_hash: hash });
    const txId = id('WTX');
    await withFallback(async () => {
      await query('INSERT INTO dapp_wallet_transactions (id, wallet_id, counterparty_address, type, asset, amount_cents, status, tx_hash, memo, metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',
        [txId, fromWalletId, to, 'external_token', asset.toUpperCase(), cents, 'completed', hash, memo || '', JSON.stringify({ tokenAddress, decimals })]);
    }, () => {});

    return { type: 'external_token', from: wallet.address, to, amount, asset, tokenAddress, txHash: hash, balance: await this.getBalance(fromWalletId) };
  }

  static async externalEthSend({ fromWalletId, toAddress, amount, memo } = {}) {
    await this.ensureTables();
    if (!fromWalletId || !toAddress) throw new Error('fromWalletId and toAddress required');
    if (!viem || !viem.isAddress || !viem.isAddress(toAddress)) throw new Error('Invalid recipient address');
    const to = viem.getAddress ? viem.getAddress(toAddress) : toAddress.toLowerCase();
    const wallet = await this.getWallet(fromWalletId);
    if (!wallet || wallet.type !== 'internal' || !wallet.private_key_encrypted) throw new Error('Only system wallets can send external ETH');
    const eth = Number(amount);
    if (eth <= 0) throw new Error('amount must be positive');

    const cfg = getConfig();
    if (!cfg.privateKey) throw new Error('DAPP_PRIVATE_KEY not configured');
    const chain = cfg.chainId === 11155111 ? chains.sepolia : chains.mainnet;
    const account = accountFns.privateKeyToAccount(this._decrypt(wallet.private_key_encrypted));
    const walletClient = viem.createWalletClient({ account, chain, transport: viem.http(cfg.rpcUrl) });
    const publicClient = viem.createPublicClient({ chain, transport: viem.http(cfg.rpcUrl) });
    const raw = viem.parseEther(String(eth));
    const fees = { maxFeePerGas: viem.parseGwei('3'), maxPriorityFeePerGas: viem.parseGwei('0.0015') };
    const ethBalance = await publicClient.getBalance({ address: wallet.address });
    const totalNeeded = raw + (fees.maxFeePerGas ? BigInt(Math.ceil(Number(fees.maxFeePerGas) * 1.5)) : 0n);
    if (ethBalance < totalNeeded) throw new Error(`Insufficient on-chain ETH balance: ${viem.formatEther(ethBalance)} available`);
    const hash = await walletClient.sendTransaction({ to, value: raw, gas: 21000n, ...fees });
    await publicClient.waitForTransactionReceipt({ hash });
    return { type: 'external_eth', from: wallet.address, to, amount: eth, asset: 'ETH', txHash: hash };
  }

  static _erc20FullAbi() {
    return [
      { type: 'function', name: 'transfer', inputs: [{ type: 'address' }, { type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'nonpayable' },
      { type: 'function', name: 'balanceOf', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
      { type: 'function', name: 'decimals', inputs: [], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
    ];
  }

  static async listTransactions(walletId) {
    await this.ensureTables();
    return withFallback(async () => {
      const rows = await query('SELECT * FROM dapp_wallet_transactions WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT 100', [walletId]);
      return rows.rows;
    }, () => []);
  }
}

module.exports = { WalletEngine };
