#!/bin/bash
# Render OpenACH's two config files from the environment and initialize the
# database on first boot. OpenACH ships db.php/security.php as commented-out
# templates meant to be hand-edited; on Northflank they are generated instead so
# no credential or encryption key lives in an image layer or in git.
#
# Required:
#   DATABASE_URL (or OPENACH_DATABASE_URL)  postgres://user:pass@host:port/db
#   OPENACH_ENCRYPTION_KEY                  encrypts every sensitive column
#   OPENACH_VALIDATION_KEY                  Yii hashing key
#
# OPENACH_ENCRYPTION_KEY cannot be rotated once data exists — the encrypted
# columns become unreadable without it.
set -euo pipefail

ROOT="${OPENACH_ROOT:-/var/www/openach}"
DB_URL="${OPENACH_DATABASE_URL:-${DATABASE_URL:-}}"

if [ -z "$DB_URL" ]; then
  echo "openach: DATABASE_URL (or OPENACH_DATABASE_URL) is required" >&2
  exit 1
fi
if [ -z "${OPENACH_ENCRYPTION_KEY:-}" ] || [ -z "${OPENACH_VALIDATION_KEY:-}" ]; then
  echo "openach: OPENACH_ENCRYPTION_KEY and OPENACH_VALIDATION_KEY are required" >&2
  exit 1
fi

# postgres://user:pass@host:port/dbname[?params]
proto_removed="${DB_URL#*://}"
creds="${proto_removed%%@*}"
hostpath="${proto_removed#*@}"
DB_USER="${creds%%:*}"
DB_PASS="${creds#*:}"
hostport="${hostpath%%/*}"
dbname="${hostpath#*/}"
DB_NAME="${dbname%%\?*}"
DB_HOST="${hostport%%:*}"
DB_PORT="${hostport#*:}"
[ "$DB_PORT" = "$DB_HOST" ] && DB_PORT=5432

# Northflank addons publish ?sslmode=require; libpq and PDO both need to be told.
DB_SSLMODE="${OPENACH_DB_SSLMODE:-}"
if [ -z "$DB_SSLMODE" ]; then
	case "$dbname" in
		*\?*) DB_SSLMODE="$(printf '%s' "${dbname#*\?}" | tr '&' '\n' | sed -n 's/^sslmode=//p' | head -1)" ;;
	esac
fi
DB_SSLMODE="${DB_SSLMODE:-prefer}"

urldecode() { printf '%b' "${1//%/\\x}"; }
DB_USER="$(urldecode "$DB_USER")"
DB_PASS="$(urldecode "$DB_PASS")"

php_quote() { printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"; }

cat > "$ROOT/protected/config/db.php" <<PHPEOF
<?php
// Generated by docker-entrypoint.sh from the environment. Do not edit.
return array(
	'connectionString' => 'pgsql:host=$(php_quote "$DB_HOST");port=$(php_quote "$DB_PORT");dbname=$(php_quote "$DB_NAME");sslmode=$(php_quote "$DB_SSLMODE")',
	'emulatePrepare' => true,
	'username' => '$(php_quote "$DB_USER")',
	'password' => '$(php_quote "$DB_PASS")',
	'charset' => 'utf8',
);
PHPEOF

cat > "$ROOT/protected/config/security.php" <<PHPEOF
<?php
// Generated by docker-entrypoint.sh from the environment. Do not edit.
return array(
	'cryptAlgorithm' => 'rijndael-256',
	'encryptionKey'  => '$(php_quote "$OPENACH_ENCRYPTION_KEY")',
	'hashAlgorithm'  => 'sha256',
	'validationKey'  => '$(php_quote "$OPENACH_VALIDATION_KEY")',
);
PHPEOF

chown www-data:www-data "$ROOT/protected/config/db.php" "$ROOT/protected/config/security.php"
chmod 640 "$ROOT/protected/config/db.php" "$ROOT/protected/config/security.php"

export PGPASSWORD="$DB_PASS"
export PGSSLMODE="$DB_SSLMODE"
psql_q() {
  psql -qtAX -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "$1"
}

for attempt in $(seq 1 30); do
  if psql_q 'SELECT 1' >/dev/null 2>&1; then break; fi
  echo "openach: waiting for postgres ($attempt/30)"
  sleep 2
done

installed="$(psql_q "SELECT to_regclass('public.user_api') IS NOT NULL;" 2>/dev/null || echo)"
if [ "$installed" != "t" ]; then
  # Applied with psql, not `yiic setup run`: that command splits the file on
  # every ';', which breaks the dollar-quoted function bodies in the schema.
  echo "openach: empty database — installing schema and seed data"
  psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
    -f "$ROOT/protected/data/schema.postgresql.sql" >/dev/null
  psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
    -f "$ROOT/protected/data/data.postgresql.sql" >/dev/null
  echo "openach: schema installed"
else
  echo "openach: schema present"
fi

# Deployment fixes on top of the upstream schema. Each file is idempotent, so
# they are replayed on every boot rather than tracked in a migrations table.
for migration in /opt/openach/migrations/*.sql; do
  [ -e "$migration" ] || continue
  echo "openach: applying $(basename "$migration")"
  psql -v ON_ERROR_STOP=1 -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
    -f "$migration" >/dev/null
done

# Yii writes its assets, logs and any SQLite state here.
chown -R www-data:www-data "$ROOT/protected/runtime" "$ROOT/assets"

exec "$@"
